### ISSUE TITLE
Setup documentation (Wiki)

### ISSUE THREAD

**Issue by BingeCode** [shuffle-project/asr-api#14]
We should start documenting our design and technology decisions.

For this purpose I will set up a Github Wiki - for starters.

This is to document the research we will do in regards to the vosk-api, whisper alternatives, whisper enhancements as well as our development decisions/policies.

**Comment by FlrnDml** [comment]
Add decisions we have written down in Notion to the wiki as well

**Comment by FlrnDml** [comment]
won't do
