### ISSUE TITLE
Configure a Test & Deploy Pipeline

### ISSUE THREAD

**Issue by FlrnDml** [shuffle-project/asr-api#3]
## Idea

We should create a Github action, or any other CI-solution, to unit-test, lint and compile our application. 
This will provide a simple solution to increase our code quality from the beginning on.

### ToDo
- Build a Deployment solution utilizing GH actions and Docker, we do only need docker for Prod deployment. (LINT,TEST,BUILD,Deploy)
- Mount Modells as docker volumes, build an initialization solution that downloads the models in deployment.
- Make sure no models are loaded while in runtime

**Comment by BingeCode** [comment]
- Unit tests only where reasonable
- Linting -> check out `black` code formatter
- Should create docker image / offer registry for the dev server to pull from later

**Comment by FlrnDml** [comment]
use default testing stack (black as formatter, pylint as linter, pyunit as unit test tool)

**Comment by FlrnDml** [comment]
https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
