### ISSUE TITLE
Check vosk-api, vosk-server projects regarding their APIs

### ISSUE THREAD

**Issue by torbenziegler** [shuffle-project/asr-api#6]
Research vosk-api. Estimate if it is a better alternative than Whisper.

Note the advantages and disadvantages of vosk for the asr-api project. Estimate what modell fits best for our needs.

- [ ] Check the api implementation and compare the API response to our current status scheme. Determine what it lacks and what we can copy from vosk

**Comment by FlrnDml** [comment]
In order to do this, we need to dig in the code. See https://github.com/alphacep/vosk-server/blob/master/client-samples/node/test.js

**Comment by torbenziegler** [comment]
I checked Vosk in combination with its server, see the results in Notion.
