### ISSUE TITLE
Implement a better solution for Sentence-End recognition

### ISSUE THREAD

**Issue by FlrnDml** [shuffle-project/asr-api#84]
Currently the websocket server prints finals as soon as a fixed time has passed. 

We should have a look if there is a better way of finding a "Sentence-End" when we want to print a final.
We should also find a way to bring the finals together, because the whole text does not make to much sense, when taking all finals as a transcript.

See the ideas from the Paper “Whispy” in our Notion or the paper [Whispy: Adapting STT Whisper Models to Real-Time Environments](https://arxiv.org/pdf/2405.03484)

We could also try the detect voide method of pydub: https://audiosegment.readthedocs.io/en/latest/audiosegment.html

We want to keep the partial / final setup as it is.

!!Attention
In case we are ready to implement this in the asr-api server, we should keep the option to use fixed final length in the config.

**Comment by hannahhielscher** [comment]
Tested the sentence-end detection through detecting the sentence-ending punctuation in the transcript and identifying the whole sentence with the timestamps. 
The transcription has too many (wrong) punctuation in the text, also the timestamps are not always exactly right, which leads to 
1. Too many detected sentences that are not really sentences
2. Wrong sentence detection through wrong timestamps

This solution is not really useful for production
