### ISSUE TITLE
Setup repository rules

### ISSUE THREAD

**Issue by torbenziegler** [shuffle-project/asr-api#9]
As discussed in the last meeting, we would like to setup a branch structure with certain rules.

E.g., main and develop branch with feature branches. Main is accessible with merge requests and approval only.

@FlrnDml I assigned you this ticket since you mentioned you wanted to setup those things

**Comment by FlrnDml** [comment]
We have now 2 branches:
Deploy and Main

Deploy is the branch we are mainting our deployed code at, all code that is pushed to deploy will be deployed. We will PR code from main only.

Main is our main branch, we will keep integrating our code here.

I setup following rules: squash commits only, no pushes to main or deploy, resolve conversations, review, do not bypass

In the future I will make code checks (PR checks) required, as soon as they are part of the codebase
